package querychecker.mistakes;

public enum Mistakes {
    TABLE_OR_COLUMN_DOES_NOT_EXIST,
    NON_FOREIGN_KEY_MERGE,
    STATEMENT_ORDER_WRONG,
    ALIAS_NO_QUOTES,
    AGGREGATION_NO_GROUP_BY,
    AGGREGATION_IN_WHERE,
    INSERT_WRONG_COLUMNS,
    INVALID_ARGUMENT_TYPE,
    UNUSED_VARIABLE,
    PART_OF_QUERY_MISSING
}
